### ISSUE TITLE
Request: add switches for calling the executeable programatically

### ISSUE THREAD

**Issue by WhitespaceQ** [Karmel0x/AsusFanControl#1]
Thank you for your work, this works in my machine (Asus X-FL)

Currently there is no switch in the app and calling the executable will print a help message.

I'm suggesting adding switches to call the executable from scripts (i.e. `--current-fan-speed print the fan speed` and `--set-fan-speed set the fan speed to n%`)

**Comment by Karmel0x** [comment]
done in commit bd0162e5f4992b428964565743733bc8925e9e01

feel free to reopen the issue if you have more suggestions about command line
