### ISSUE TITLE
how it works?

### ISSUE THREAD

**Issue by Satyajeet1152000** [Karmel0x/AsusFanControl#10]
I own an Asus Vivobook 14 X412DA and had been trying to control its fan speed for a while. Despite experimenting with various third-party software and different settings, I couldn't find a solution. I spent months searching for a fan speed controller without success. However, I recently came across your software, and thankfully, it worked.

I've always wondered how the MyAsus app manages to control fan speed under the Fan Diagnosis option when third-party solutions seem unable to do so. I'm curious to learn from you how you discovered this solution and how your software operates? I would greatly appreciate it if you could share your insights with me.

THANK YOU VERY MUCH.

**Comment by Karmel0x** [comment]
I couldn't find fan control app for my laptop too.
I've found that there is available [Fan Diagnosis](https://github.com/Karmel0x/AsusFanControl/assets/25367564/7129833b-97af-4da8-9148-b71e49552ea4) in [MyASUS](https://apps.microsoft.com/store/detail/myasus/9N7R5S6B0ZZH) application.

To find how it works I've checked several things. If I remember correct - application is using some service to control fans. I've checked dependencies of it using [Dependency Walker](https://www.dependencywalker.com/), then used [IDA disassembler](https://hex-rays.com/ida-free/) to check exports in them.

It's easy to guess which dll using names of exported function is used for controlling fans - `AsusWinIO64.dll`.
