### ISSUE TITLE
Feature Request: Poll RPM and CPU temp periodically

### ISSUE THREAD

**Issue by headquarter8302** [Karmel0x/AsusFanControl#19]
At the moment, one needs to manually refresh the stats in order to get their information updated. It would be nice if there's an option (or even just by default) to poll these stats on a set period, 1000ms would be nice

**Comment by Matiszp** [comment]
I have added this functionality myself in a fork. I've added an "Autorefresh" option under the advanced tab. You can find it here:
https://github.com/Matiszp/AsusFanControl/releases/tag/v4
![image](https://github.com/Karmel0x/AsusFanControl/assets/171484063/a3d555b0-c840-454f-8f45-ba6e21a4154f)

**Comment by Karmel0x** [comment]
done in 22f488173d60c423b756b5020c0fe779ac7c4988
