### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by Dorlander** [Karmel0x/AsusFanControl#2]
after using the program, my fans stopped working after a reboot

**Comment by Dorlander** [comment]
only with this program

**Comment by Karmel0x** [comment]
you mean it stopped working entirely? 0 rpm?
or you mean fan control settings has stopped working?
tell me your laptop model please

**Comment by Dorlander** [comment]
> you mean it stopped working entirely? 0 rpm? or you just mean that fan control settings are not applied after reboot?
yes, 0 rpm, now i must use manual control with this prog
> tell me your laptop model and operating system please
asus fx705dy

**Comment by Karmel0x** [comment]
looks like some models don't have persistent memory for `fan speed` but have memory for `test mode` which results to fan being set to 0%
for the fan to start working again, it is needed to turn on the program and turn off the fan control

**Comment by Dorlander** [comment]
Yep, fixed tnx)

ср, 8 нояб. 2023 г., 03:31 Karmel0x ***@***.***>:

**Comment by WhitespaceQ** [comment]
@Dorlander this will also "disables" your fan if you sleep/hibernates while test mode is on. My workaround is to set a Task Scheduler that monitors Microsoft-Windows-Kernel-Power, Event ID 107 (triggered on wake after sleep/hibernate) to call AsusFanControl and turn off test mode.
