### ISSUE TITLE
Not Working for both fans 

### ISSUE THREAD

**Issue by SubhenduX** [Karmel0x/AsusFanControl#20]
I have Asus Tuf F15 and it got 2 fans when i use it it only turns one fan not both fans

**Comment by BrightenedDay** [comment]
I got this issue too. All I had to do was move the slider a bit after enabling it and the second fan would start.

**Comment by SubhenduX** [comment]
Thanks bro. It worked. ♥️

**Comment by SubhenduX** [comment]
Still i would like to stay open so that if anyone can make changes and fix this bug.

**Comment by BrightenedDay** [comment]
I tried to fix it in my fork. I just flipped the order in the function that sets the fans, and that worked for me, but I'm not sure about anyone else. The problem I had was that on startup it still only set the first fan in the index.

**Comment by Karmel0x** [comment]
~~I've added delay between choosing fan and setting speed in 22f488173d60c423b756b5020c0fe779ac7c4988~~
I've added delay between setting speed for each fan in 76893a7389bcf79033fca5d290e4394abb4ef209
please check if it's working properly for you now
I have only 1 fan so I can't test it

**Comment by SubhenduX** [comment]
Thank You Its Working Now Tested it
