### ISSUE TITLE
is Linux support possible? 

### ISSUE THREAD

**Issue by GizakiF** [Karmel0x/AsusFanControl#22]

**Comment by Karmel0x** [comment]
unfortunately not, unless you can install `ASUS System Control Interface Driver` there

**Comment by headquarter8302** [comment]
AsusFanControl is merely a front-end for ~~interfacing~~ _cough cough tampering cough cough_ with ASUS's fan control drivers. So unless ASUS or the Linux kernel provides a way to modify ASUS motherboard fans parameters there, I don't think this'll be possible

**Comment by stem11-smc** [comment]
https://github.com/Arkapravo-Ghosh/asus-fan-mode
