### ISSUE TITLE
Would that work on Scar 18 in addition to other programs?

### ISSUE THREAD

**Issue by SynStark** [Karmel0x/AsusFanControl#23]
Hello!
Thank you for the program.

I have a quick question. I have the Scar 18 13980HX 4090.
I've deleted all the Asus software and use only GHelper and Throttlestop.
Will this software work in combination with the rest?

Thank you!

**Comment by Karmel0x** [comment]
tbh. I dont know what you mean

**Comment by headquarter8302** [comment]
If the ASUS system DLL is still present and the ASUS service (both mentioned in the readme) is still running, then it should work.

If any of the two above isn't available, the fan control probably wouldn't work
