### ISSUE TITLE
No longer works suddenly

### ISSUE THREAD

**Issue by adinsapo** [Karmel0x/AsusFanControl#24]
Quit opening after computer overheated, but worked before
Tried reinstalling, did not do anything, has worked for months before.

ROG Zephyrus G16 GU603VV

**Comment by Karmel0x** [comment]
if fan control is not working try reinstalling [ASUS System Control Interface](https://dlcdnets.asus.com/pub/ASUS/nb/Image/Software/SoftwareandUtility/15971/ASUSSystemControlInterfacev3_ASUS_Z_V3.1.32.0_15971.exe)

if application won't run try deleting program data which may be corrupted `%appdata%\..\Local\AsusFanControlGUI`

**Comment by adinsapo** [comment]
Program data was corrupted, thanks
