### ISSUE TITLE
Asus FX506IV: Can't set low fan speed

### ISSUE THREAD

**Issue by CyberAndrew** [Karmel0x/AsusFanControl#3]
When I set 40% in gui, fan speed is 3200 rpm. But my laptop fan's can operate at lower speeds when there is no load.
One need to operate at lower speeds.

**Comment by CyberAndrew** [comment]
The problem doesn't appears on command line version of program. Only in GUI.

**Comment by Karmel0x** [comment]
I've added option to ignore this limit in 5a17ba223f7f2258bfc858e6938b3d280309db37

![image](https://github.com/Karmel0x/AsusFanControl/assets/25367564/ebd9d183-9721-4c20-802c-4537ff11ef6d)
