### ISSUE TITLE
Request for a "minimize to tray" option

### ISSUE THREAD

**Issue by mertzi** [Karmel0x/AsusFanControl#7]
Hi!

I'm sorry for creating an issue but I didn't find any other means to contact you. This app is a life saver, I love to be able to set a static rpm, I deeply hate fans that keeps switching the rpm going up and down. 
I don't have an overheating issue, quite the opposite, but the fans are ramping up at a way too low temperature, like all manufacturers scared of a little heat do.
The MyAsus preset "whisper quiet" is definitely not whisper quiet. But your app lets me set a 10% static fan at ~300 rpm, which is completely inaudible but the temp stays way below 50C at light work. For some reason when I set the slider below 10 the program is overridden and the fan goes instantly to the ridiculous rpm of 1900 despite the CPU being very cool.
Anyhow, my request is an option to minimize your program to the system tray, because I like to keep it open and change to a higher static RPM when I require a little more performance. What would be even more fantastic is to let us save presets. I suspect having a fan curve option is more difficult, it doesn't work with G helper, but I'm more than fine with static rpms.

Thank you for this app!

**Comment by dspwhite** [comment]
This program is a lifesaver. The fan would normally keep whirring in and out, and I could hear the pitch rising and falling like crazy.

Anyway, let me lend my support to allowing the app to minimize to tray, and hopefully for it to display the CPU temp number while in the tray.

For some reason, I can't set the CPU speed below 40% in the GUI version, but I can in the CLI version. Please fix that too!

**Comment by Karmel0x** [comment]
"minimize to tray" option done in 22f488173d60c423b756b5020c0fe779ac7c4988
to set CPU speed below 40% uncheck "Forbid unsafe settings" option
